### ISSUE TITLE
Cannot browse files

### ISSUE THREAD

**Issue by maerzhas3** [vdparikh/XBMCee.iOS#7]
Hi, I cannot browse files on the ipad (using raspbmc). When clicking "browse files/sources", a window named "sources" opens which allows choosing only a single option, "music addons". How do I set xbmcee up such that i can browse folders 'n files?

**Comment by vdparikh** [comment]
Do you have folders setup on raspbmc? Are you able to browse/see folders on your XBMC

**Comment by maerzhas3** [comment]
with folders setup it works - thanks :)

**Comment by vdparikh** [comment]
Nice... Glad it worked out
